version: '3'
services: 
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    expose:
      - "5000"
  apirest:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes: 
      - ./backend/src:/app/api
      - ./backend/package.json:/app/package.json
    environment:
      - WORKER_HOST=worker
      - WORKER_PORT=5000
    depends_on: 
      - worker
    #ports: 
    #  - "3001:3001"
  site:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: ./Supercalculadora
    volumes: 
      - ./Supercalculadora/public:/app/public
      - ./Supercalculadora/src:/app/src
      - ./Supercalculadora/views:/app/views
      - ./Supercalculadora/package.json:/app/package.json
    #ports: 
    #  - "80:3000"
  nginx:
    depends_on: 
      - site
      - apirest
      - worker
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./NGINX
    ports: 
      - "80:80"